### ISSUE TITLE
Typo on blog post (v1.13 Experimental FFI)

### ISSUE THREAD

**Issue by sant123** [denoland/dotland#1825]
Hi, I think I found some typos inside the examples for the new FFI feature.
``` sh
cc -shared -Wl -o add_numbers.so add_numbers.o
```

If passed -Wl without comma-separated options it will throw like this:
`gcc: error: unrecognized command-line option ‘-Wl’; did you mean ‘-W’?`

So maybe just set it at:
``` sh
cc -shared -o add_numbers.so add_numbers.o
```

And `libName` const should contain a local import (`./`): 

``` ts
const libName = `./add_numbers.${libSuffix}`;
```

If not `Deno.dlopen` will throw:

``` sh
error: Uncaught Error: Could not open library: add_numbers.so: cannot open shared object file: No such file or directory
const dylib = Deno.dlopen(libName, {
                   ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at new DynamicLibrary (deno:extensions/ffi/00_ffi.js:12:24)
    at Object.dlopen (deno:extensions/ffi/00_ffi.js:26:12)
    at file:///home/sant821/Desktop/projects/testing-ffi/mod.ts:9:20
```

**Comment by littledivy** [comment]
Sorry for the delay, fixed.
