### ISSUE TITLE
Dev server seems not work on OSX

### ISSUE THREAD

**Issue by hashrock** [denoland/dotland#2368]
- M1 Mac Monterey
- deno 1.24.2 (release, aarch64-apple-darwin)
- v8 10.4.132.20
- typescript 4.7.4

I got this error when I run `deno task start`

```
Listening on http://localhost:8000/
An error occured during route handling or page rendering. Error: <Head> component is not supported in the browser, or during suspense renders.
    at Object.Head (https://fresh.deno.dev/@1.0.0-rc.4/src/runtime/head.ts:15:11)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:916)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at m (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:3:671)
    at render (https://fresh.deno.dev/@1.0.0-rc.4/src/server/render.tsx:177:16)
    at Object.render [as renderFn] (file:///Users/hash/Documents/GitHub/dotland/options.ts:16:3)
    at render (https://fresh.deno.dev/@1.0.0-rc.4/src/server/render.tsx:181:14)
Caused by TypeError: Cannot read properties of undefined (reading 'context')
    at w (https://esm.sh/v90/preact@10.10.0/deno/hooks.js:2:1043)
    at Object.Head (https://fresh.deno.dev/@1.0.0-rc.4/src/runtime/head.ts:13:15)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:916)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at h (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:4:1044)
    at m (https://esm.sh/v90/preact-render-to-string@5.1.20/X-ZC9wcmVhY3RAMTAuOC4x/deno/preact-render-to-string.js:3:671)
    at render (https://fresh.deno.dev/@1.0.0-rc.4/src/server/render.tsx:177:16)
    at Object.render [as renderFn] (file:///Users/hash/Documents/GitHub/dotland/options.ts:16:3)
```

updating the import map (imitating dotcom repo) solved my issue, but I'm not sure this is the right solution.

>    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.1.20?external=preact",

**Comment by hashrock** [comment]
Sorry, I think it was a cache issue.
