### ISSUE TITLE
500 Error: https://deno.land/x/funql@0.0.15

### ISSUE THREAD

**Issue by kitsonk** [denoland/dotland#2556]
The URL https://deno.land/x/funql@0.0.15 is returning a 500 error.

**Comment by crowlKats** [comment]
For more context:
```
SyntaxError: Unexpected non-whitespace character after JSON at position 3
    at parse (<anonymous>)
    at packageData (deno:ext/fetch/22_body.js:359:16)
    at consumeBody (deno:ext/fetch/22_body.js:236:14)
    at async GET (file:///Users/crowlkats/projects/deno/denoland/dotland/routes/x/module.tsx:196:22)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:228:22
    at async Server.<anonymous> (file:///Users/crowlkats/projects/deno/denoland/dotland/util/ga_utils.ts:198:13)
    at async Server.#respond (https://deno.land/std@0.143.0/http/server.ts:298:18)
```

**Comment by kitsonk** [comment]
It is fetching: https://apiland.deno.dev/v2/pages/mod/info/funql/0.0.15/

and getting back:

```
502: Bad Gateway (DEPLOYMENT_FAILED)

The deployment failed while serving the request.
```
