### ISSUE TITLE
The error page is shown when the code block has unknown language tag

### ISSUE THREAD

**Issue by liruifengv** [denoland/dotland#2616]
I visit this page https://deno.land/std@0.167.0/encoding/front_matter/mod.ts, but it reports an error, and the HTTP request is 500.

![image](https://user-images.githubusercontent.com/25167721/205875700-4934f1f3-2a1f-474f-baf2-6d999522d25c.png)

![image](https://user-images.githubusercontent.com/25167721/205875926-621e9534-406f-42c2-b8ab-7134df7b79e9.png)

I don't know if I should ask the question here or in `deno_std`.

**Comment by justjavac** [comment]
error message:

```
An error occured during route handling or page rendering.

Error: Unknown language: `ignore` is not registered
    at a (https://esm.sh/v87/fault@2.0.1/deno/fault.js:2:307)
    at Object.u [as highlight] (https://esm.sh/v87/lowlight@2.7.0/deno/lowlight.js:2:2810)
    at syntaxHighlight (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:30:27)
    at Object.mdToHtml (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:97:10)
    at Object.Markdown (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:135:26)
    at https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
    at E (https://esm.sh/v96/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
```

**Comment by liruifengv** [comment]
I created a pr to fix this in `deno_std`. 
Thanks @justjavac

**Comment by kt3k** [comment]
I'm reopening this issue. We shouldn't show error page when there's unknown language tag. We should show non syntax highlighted code block instead.

**Comment by liruifengv** [comment]
Maybe we can handle this error in deno_doc_components? set a default tag?

**Comment by crowlKats** [comment]
Closing as this has been fixed
